<?php

/**
 * GameConSuite Admin API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.org](https://gameconsuite.org)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractAttendeeApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractAttendeeApi
{

    /**
     * @var ContainerInterface|null Slim app container instance
     */
    protected $container;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface|null $container Slim app container instance
     */
    public function __construct(ContainerInterface $container = null)
    {
        $this->container = $container;
    }


    /**
     * POST addItemToCart
     * Summary: Add an item to the cart
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function addItemToCart(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $body = $request->getParsedBody();
        $message = "How about implementing addItemToCart as a POST method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST createUserEnvelope
     * Summary: Create envelope
     * Notes: create an envelope for current user
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createUserEnvelope(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing createUserEnvelope as a POST method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT editEnvelopeByMember
     * Summary: Modify envelop details authorized for the current logged in user
     * Output-Formats: [application/xml, application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function editEnvelopeByMember(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $body = $request->getParsedBody();
        $message = "How about implementing editEnvelopeByMember as a PUT method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getAuthorizationByMember
     * Summary: Get the authorization list for the specified member
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getAuthorizationByMember(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $message = "How about implementing getAuthorizationByMember as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getCartByMember
     * Summary: Get the cart for the specified member
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getCartByMember(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $message = "How about implementing getCartByMember as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getEnvelopeByMember
     * Summary: Get the envelop details for the logged in user
     * Output-Formats: [application/xml, application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getEnvelopeByMember(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $message = "How about implementing getEnvelopeByMember as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getScheduleByMember
     * Summary: Get the complete schedule for the specified member
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getScheduleByMember(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $message = "How about implementing getScheduleByMember as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getUserEnvelopes
     * Summary: Get list of attendee envelopes
     * Notes: List the attendees envelopes for the logged in user
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getUserEnvelopes(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing getUserEnvelopes as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getUserTickets
     * Summary: Get envelopes with tickets
     * Notes: Get list of attendee envelopes and all the tickets for each
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getUserTickets(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing getUserTickets as a GET method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE removeItemFromCart
     * Summary: Remove item from cart
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function removeItemFromCart(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $itemId = $args['itemId'];
        $message = "How about implementing removeItemFromCart as a DELETE method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PATCH updateItemFromCart
     * Summary: Change the quantity of an item in the cart
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateItemFromCart(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $itemId = $args['itemId'];
        $message = "How about implementing updateItemFromCart as a PATCH method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE userEnvelopeMemberIdDelete
     * Summary: Remove the envelope for the logged in user
     * Notes: Remove or archive the envelope for the current user under certain conditions
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function userEnvelopeMemberIdDelete(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $memberId = $args['memberId'];
        $message = "How about implementing userEnvelopeMemberIdDelete as a DELETE method in OpenAPIServer\Api\AttendeeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
