<?php

/**
 * MemberApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * GameConSuite Admin API
 *
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.com](https://gameconsuite.com)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model;

/**
 * MemberApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\MemberApi
 */
class MemberApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass() : void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp() : void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown() : void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }

    /**
     * Test case for createMember
     *
     * Create a new member.
     *
     * @covers ::createMember
     */
    public function testCreateMember()
    {
    }

    /**
     * Test case for deleteMember
     *
     * Removes a member.
     *
     * @covers ::deleteMember
     */
    public function testDeleteMember()
    {
    }

    /**
     * Test case for updateMember
     *
     * Update an existing member.
     *
     * @covers ::updateMember
     */
    public function testUpdateMember()
    {
    }

    /**
     * Test case for updateMemberWithForm
     *
     * Updates a member with form data.
     *
     * @covers ::updateMemberWithForm
     */
    public function testUpdateMemberWithForm()
    {
    }
}
