<?php

/**
 * GameConSuite Admin API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.org](https://gameconsuite.org)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * CartItem
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CartItem extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "conventionId", "id", "memberId", "price", "quantity", "subtype", "type" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "conventionId" : {
      "type" : "integer",
      "format" : "int32"
    },
    "memberId" : {
      "type" : "integer",
      "format" : "int64"
    },
    "type" : {
      "type" : "string"
    },
    "subtype" : {
      "type" : "string",
      "description" : "for tickets, this is the id of the event"
    },
    "quantity" : {
      "type" : "integer",
      "format" : "int32"
    },
    "price" : {
      "type" : "number",
      "format" : "float"
    },
    "special" : {
      "type" : "string",
      "description" : "for badges, the name on the badge"
    },
    "event" : {
      "$ref" : "#/components/schemas/Event"
    }
  }
}
SCHEMA;
}
