<?php

/**
 * GameConSuite Admin API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.org](https://gameconsuite.org)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * EventAdminAllOf
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class EventAdminAllOf extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "s_comments" : {
      "type" : "string",
      "description" : "Comments from GM to scheduler about event"
    },
    "s_setup" : {
      "description" : "Request from GM about space setup"
    },
    "s_table_type" : {
      "type" : "string",
      "description" : "Request from GM about type of table"
    },
    "s_eventcom" : {
      "type" : "string",
      "description" : "Comments from GM to scheduler about scheduling"
    },
    "b_approval" : {
      "type" : "boolean",
      "description" : "true if event is approved for public release"
    },
    "b_edited" : {
      "type" : "boolean",
      "description" : "true if copy editing is complete"
    },
    "i_c1" : {
      "type" : "integer",
      "description" : "1st choice for time slot",
      "format" : "int32"
    },
    "i_c2" : {
      "type" : "integer",
      "description" : "2nd choice for time slot",
      "format" : "int32"
    },
    "i_c3" : {
      "type" : "integer",
      "description" : "3rd choice for time slot",
      "format" : "int32"
    },
    "i_profit" : {
      "type" : "number",
      "format" : "float"
    },
    "i_actual" : {
      "type" : "integer",
      "description" : "Event attendance entered by event runner",
      "format" : "int32"
    },
    "b_showed_up" : {
      "type" : "boolean",
      "description" : "Entered by event runner, true if GM showed up"
    },
    "b_prize" : {
      "type" : "integer",
      "description" : "Entered by event runner, number of prize tokens awarded",
      "format" : "int32"
    },
    "s_note" : {
      "type" : "string"
    },
    "d_updated" : {
      "type" : "string",
      "description" : "Date the event was last updated",
      "format" : "date-time"
    },
    "d_created" : {
      "type" : "string",
      "description" : "Date the event was submitted",
      "format" : "date-time"
    }
  }
}
SCHEMA;
}
