<?php

/**
 * Event
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Event
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Event implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "ages", "category", "conventionId", "duration", "game", "gm", "id", "maxplayers" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "conventionId" : {
      "type" : "integer",
      "format" : "int32"
    },
    "category" : {
      "$ref" : "#/components/schemas/Category"
    },
    "gm" : {
      "$ref" : "#/components/schemas/Member"
    },
    "game" : {
      "type" : "string",
      "example" : "7 Wonders"
    },
    "title" : {
      "type" : "string",
      "example" : "Leaders"
    },
    "tags" : {
      "type" : "array",
      "xml" : {
        "name" : "tag",
        "wrapped" : true
      },
      "items" : {
        "$ref" : "#/components/schemas/Tag"
      }
    },
    "day" : {
      "type" : "string",
      "description" : "day of the event",
      "enum" : [ "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" ]
    },
    "time" : {
      "type" : "number",
      "description" : "Start time of event, as first 2 digits of event time in 24 hour clock",
      "format" : "float"
    },
    "endtime" : {
      "type" : "number",
      "description" : "End time of event, as first 2 digits of event time in 24 hour clock",
      "format" : "float"
    },
    "duration" : {
      "type" : "number",
      "format" : "float"
    },
    "maxplayers" : {
      "type" : "integer",
      "description" : "the number of seats available in the game, must be larger than minplayers",
      "format" : "int32"
    },
    "minplayers" : {
      "type" : "integer",
      "description" : "the minimum number of player required to play the game",
      "format" : "int32"
    },
    "desclong" : {
      "type" : "string"
    },
    "descshort" : {
      "type" : "string"
    },
    "exper" : {
      "type" : "string",
      "description" : "experience rating (1, 3, 5), where 1 is the least experience",
      "enum" : [ "1", "3", "5" ]
    },
    "complex" : {
      "type" : "string",
      "description" : "complexity rating (A, C, E), where A is the least complex",
      "enum" : [ "A", "C", "E" ]
    },
    "room" : {
      "$ref" : "#/components/schemas/Room"
    },
    "table" : {
      "type" : "string"
    },
    "ages" : {
      "type" : "integer",
      "description" : "the minimum age recommended by the gamemaster (7,13,18,19/Mature)",
      "format" : "int32"
    },
    "cost" : {
      "type" : "number",
      "description" : "Price of event ticket",
      "format" : "float"
    },
    "fill" : {
      "type" : "number",
      "description" : "the number of seats filled, when enabled",
      "format" : "int(32)"
    },
    "soldout" : {
      "type" : "boolean",
      "description" : "true if event has no seats available"
    }
  },
  "xml" : {
    "name" : "Event"
  }
}
SCHEMA;

    /** @var int $id */
    public $id;

    /** @var int $conventionId */
    public $conventionId;

    /** @var \OpenAPIServer\Model\Category $category */
    public $category;

    /** @var \OpenAPIServer\Model\Member $gm */
    public $gm;

    /** @var string $game */
    public $game;

    /** @var string $title */
    public $title;

    /** @var \OpenAPIServer\Model\Tag[] $tags */
    public $tags;

    /** @var string $day day of the event*/
    public $day;

    /** @var float $time Start time of event, as first 2 digits of event time in 24 hour clock*/
    public $time;

    /** @var float $endtime End time of event, as first 2 digits of event time in 24 hour clock*/
    public $endtime;

    /** @var float $duration */
    public $duration;

    /** @var int $maxplayers the number of seats available in the game, must be larger than minplayers*/
    public $maxplayers;

    /** @var int $minplayers the minimum number of player required to play the game*/
    public $minplayers;

    /** @var string $desclong */
    public $desclong;

    /** @var string $descshort */
    public $descshort;

    /** @var string $exper experience rating (1, 3, 5), where 1 is the least experience*/
    public $exper;

    /** @var string $complex complexity rating (A, C, E), where A is the least complex*/
    public $complex;

    /** @var \OpenAPIServer\Model\Room $room */
    public $room;

    /** @var string $table */
    public $table;

    /** @var int $ages the minimum age recommended by the gamemaster (7,13,18,19/Mature)*/
    public $ages;

    /** @var float $cost Price of event ticket*/
    public $cost;

    /** @var float $fill the number of seats filled, when enabled*/
    //public $fill;

    /** @var bool $soldout true if event has no seats available*/
    //public $soldout;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
