<?php

/**
 * EventAdmin
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * EventAdmin
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class EventAdmin implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "allOf" : [ {
    "$ref" : "#/components/schemas/EventPrivate"
  }, {
    "$ref" : "#/components/schemas/EventAdmin_allOf"
  } ]
}
SCHEMA;

    /** @var int $id */
    private $id;

    /** @var int $conventionId */
    private $conventionId;

    /** @var \OpenAPIServer\Model\Category $category */
    private $category;

    /** @var \OpenAPIServer\Model\Member $gm */
    private $gm;

    /** @var string $game */
    private $game;

    /** @var string $title */
    private $title;

    /** @var \OpenAPIServer\Model\Tag[] $tags */
    private $tags;

    /** @var string $day day of the event*/
    private $day;

    /** @var float $time Start time of event, as first 2 digits of event time in 24 hour clock*/
    private $time;

    /** @var float $endtime End time of event, as first 2 digits of event time in 24 hour clock*/
    private $endtime;

    /** @var float $duration */
    private $duration;

    /** @var int $maxplayers the number of seats available in the game, must be larger than minplayers*/
    private $maxplayers;

    /** @var int $minplayers the minimum number of player required to play the game*/
    private $minplayers;

    /** @var string $desclong */
    private $desclong;

    /** @var string $descshort */
    private $descshort;

    /** @var string $exper experience rating (1, 3, 5), where 1 is the least experience*/
    private $exper;

    /** @var string $complex complexity rating (A, C, E), where A is the least complex*/
    private $complex;

    /** @var \OpenAPIServer\Model\Room $room */
    private $room;

    /** @var string $table */
    private $table;

    /** @var float $cost Price of event ticket*/
    private $cost;

    /** @var string $vttLink A link to VTT information, available only to GMs and ticketed players*/
    private $vttLink;

    /** @var string $vttInfo Additional VTT information, available only to GMs and ticketed players*/
    private $vttInfo;

    /** @var string $sComments Comments from GM to scheduler about event*/
    private $sComments;

    /** @var AnyType $sSetup Request from GM about space setup*/
    private $sSetup;

    /** @var string $sTableType Request from GM about type of table*/
    private $sTableType;

    /** @var string $sEventcom Comments from GM to scheduler about scheduling*/
    private $sEventcom;

    /** @var bool $bApproval true if event is approved for public release*/
    private $bApproval;

    /** @var bool $bEdited true if copy editing is complete*/
    private $bEdited;

    /** @var int $iC1 1st choice for time slot*/
    private $iC1;

    /** @var int $iC2 2nd choice for time slot*/
    private $iC2;

    /** @var int $iC3 3rd choice for time slot*/
    private $iC3;

    /** @var float $iProfit */
    private $iProfit;

    /** @var int $iActual Event attendance entered by event runner*/
    private $iActual;

    /** @var bool $bShowedUp Entered by event runner, true if GM showed up*/
    private $bShowedUp;

    /** @var int $bPrize Entered by event runner, number of prize tokens awarded*/
    private $bPrize;

    /** @var string $sNote */
    private $sNote;

    /** @var \DateTime $dUpdated Date the event was last updated*/
    private $dUpdated;

    /** @var \DateTime $dCreated Date the event was submitted*/
    private $dCreated;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
