<?php

/**
 * Event
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Event
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Event extends PublicEvent implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "category", "desclong", "descshort", "game", "gm", "maxplayers", "minplayers", "name" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "category" : {
      "$ref" : "#/components/schemas/Category"
    },
    "gm" : {
      "$ref" : "#/components/schemas/Member"
    },
    "game" : {
      "type" : "string",
      "example" : "7 Wonders"
    },
    "title" : {
      "type" : "string",
      "example" : "Leaders"
    },
    "tags" : {
      "type" : "array",
      "xml" : {
        "name" : "tag",
        "wrapped" : true
      },
      "items" : {
        "$ref" : "#/components/schemas/Tag"
      }
    },
    "day" : {
      "type" : "string",
      "description" : "day of the event",
      "enum" : [ "FRI", "SAT", "SUN" ]
    },
    "time" : {
      "type" : "integer",
      "description" : "first 2 digits of event time in 24 hour clock",
      "format" : "int64"
    },
    "room" : {
      "$ref" : "#/components/schemas/Room"
    },
    "table" : {
      "type" : "string"
    },
    "maxplayers" : {
      "type" : "integer",
      "description" : "the number of seats available in the game, must be larger than minplayers",
      "format" : "int64"
    },
    "minplayers" : {
      "type" : "integer",
      "description" : "the minimum number of player required to play the game",
      "format" : "int64"
    },
    "desclong" : {
      "type" : "string"
    },
    "descshort" : {
      "type" : "string"
    },
    "duration" : {
      "type" : "number",
      "format" : "float"
    }
  },
  "xml" : {
    "name" : "Event"
  }
}
SCHEMA;

    /** @var int $id */
    public $id;

    /** @var \OpenAPIServer\Model\Category $category */
    public $category;

    /** @var \OpenAPIServer\Model\Member $gm */
    public $gm;

    /** @var string $game */
    public $game;

    /** @var string $title */
    public $title;

    /** @var \OpenAPIServer\Model\Tag[] $tags */
    public $tags;

    /** @var string $day day of the event*/
    public $day;

    /** @var int $time first 2 digits of event time in 24 hour clock*/
    public $time;

    /** @var \OpenAPIServer\Model\Room $room */
    public $room;

    /** @var string $table */
    public $table;

    /** @var int $maxplayers the number of seats available in the game, must be larger than minplayers*/
    public $maxplayers;

    /** @var int $minplayers the minimum number of player required to play the game*/
    public $minplayers;

    /** @var string $desclong */
    public $desclong;

    /** @var string $descshort */
    public $descshort;

    /** @var float $duration */
    public $duration;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
