<?php

/**
 * AbstractSystemApi
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * GameConSuite Admin API
 *
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.com](https://gameconsuite.com)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use OpenAPIServer\Repository\TagRepository;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exception;



// TODO FIXME find a better way to do this
$config = $GLOBALS['config'];
include __DIR__.'/../../../inc/resources/event/constants.php';
$GLOBALS['constants'] = $constants;
//echo print_r($GLOBALS['constants'],1);

/**
 * AbstractSystemApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SystemApi extends AbstractSystemApi
{

    /**
     * @var ContainerInterface|null Slim app container instance
     */
    protected $container;

    protected $siteConfiguration;
    protected $eventConstants;
    protected $tagRepository;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface|null $container Slim app container instance
     */
    public function __construct(ContainerInterface $container = null, TagRepository $tagRepository)
    {
        $this->container = $container;
        $this->siteConfiguration = $GLOBALS['config']; // TODO pass through dependency injection
        $this->eventConstants = array_merge($GLOBALS['constants']['events']);
        $this->tagRepository = $tagRepository;
    }


    /**
     * GET getEventsConstants
     * Summary: Provide keys/value pairs for event-related configuration options
     * Notes: Returns an object containing key/value lookup for various event-related options
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function getEventsConstants(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $abbrDays = (key_exists('abbrDays', $queryParams)) ? $queryParams['abbrDays'] : null;
        $fullExpComp = (key_exists('fullExpComp', $queryParams)) ? $queryParams['fullExpComp'] : null;

        $answer = [];
        $answer['eventType'] = $this->eventConstants['event_types'];

        if ($abbrDays) {
            $answer['days'] = $this->eventConstants['daysAbbreviated'];
        } else {
            $answer['days'] = $this->eventConstants['days'];
        }

        $answer['ages'] = $this->eventConstants['agesNoBlank'];
        $answer['agesInDesc'] = $this->eventConstants['agesInBook'];
        unset($answer['agesInDesc'][0]); // unset the blank

        if($fullExpComp) {
            $answer['exper'] = $this->eventConstants['experience']['display'];
            $answer['complex'] = $this->eventConstants['complexity']['display'];
        } else {
            $answer['exper'] = $this->eventConstants['experience']['select'];
            $answer['complex'] = $this->eventConstants['complexity']['select'];
        }

        // TODO add tag information
        $answer['tagsInUse'] = $this->tagRepository->getCurrentTagsInUse();

        // TODO add slot options, with selection for the duration

        // $message = "How about implementing getEventsConstants as a GET method in OpenAPIServer\Api\SystemApi class?";
        // throw new Exception($message);

        $response->getBody()->write(json_encode($answer));
        return $response->withStatus(200)->withHeader('Content-type', 'application/json');
    }
}
