<?php

/**
 * GameConSuite Admin API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is the administrative API for GameConSuite.  You can find out more about Game Con Suite at  [https://gameconsuite.org](https://gameconsuite.org)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Member;

/**
 * MemberTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Member
 */
class MemberTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Member"
     */
    public function testMember()
    {
        $testMember = new Member();
        $namespacedClassname = Member::getModelsNamespace() . '\\Member';
        $this->assertSame('\\' . Member::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Member" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "Member" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
        $this->markTestIncomplete(
            'Test of "firstName" property in "Member" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
        $this->markTestIncomplete(
            'Test of "lastName" property in "Member" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "groupName"
     */
    public function testPropertyGroupName()
    {
        $this->markTestIncomplete(
            'Test of "groupName" property in "Member" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Member::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
