name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_ADAPTER: mysql
      DB_HOST: 127.0.0.1
      DB_NAME: ucon_test
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ucon_test
        ports:
          - 3306/tcp

    steps:
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        php_version: 7.3
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create a test database
      run: mysql --host 127.0.0.1 -uroot -ppassword -e "create database ucon_test"

    - name: Install dependencies for base application
      run: composer install --prefer-dist --no-progress

    - name: Install depedencies in API directory
      run: cd api; composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: cd api; composer test
